// src/components/GameBoard.tsx
import { useEffect, useState } from 'react'
import { colors, type Color } from '../model/deck'
import type { BoardState } from '../model/board'
import UnoCard from './UnoCard'

//#region Props

type Props = {
  state: BoardState
  busy?: boolean
  onPlay: (index: number, color?: Color) => void
  onDraw: () => void
  onPass: () => void
  onUno: () => void
  onCatch: (player: number) => void
  onChallenge: () => void
  onAccept: () => void
}

//#endregion

export default function GameBoard({
  state, busy = false, onPlay, onDraw, onPass, onUno, onCatch, onChallenge, onAccept
}: Props)
{
  const [selectedCard, setSelectedCard] = useState<number>()

  useEffect(() => setSelectedCard(undefined), [state])

  const opponents = state.players.map((name, index) => ({ name, index }))
    .filter(player => player.index !== state.playerIndex)
  const inTurn = state.playerInTurn === state.playerIndex
  const mustAnswer = state.wildDrawFourChallenger === state.playerIndex

  function selectCard(index: number): void
  {
    if (busy || !state.playableCards.includes(index)) return

    if ('color' in state.hand[index]) onPlay(index)
    else setSelectedCard(index)
  }

  return <section className="game-board">
    <h2>Round in progress</h2>

    <div className="opponents">
      {opponents.map(({ name, index }) =>
        <article
          key={index}
          className={`opponent ${state.playerInTurn === index ? 'active' : ''}`}
        >
          <h3>{name}</h3>
          <p>{state.handSizes[index]} cards</p>
          {state.playerInTurn === index && <span>In turn</span>}
          {state.handSizes[index] === 1 &&
            <button disabled={busy} onClick={() => onCatch(index)}>
              Catch missed UNO
            </button>}
        </article>)}
    </div>

    <div className="round-status" aria-live="polite">
      {state.playerInTurn != null &&
        <p><strong>{state.players[state.playerInTurn]}'s turn</strong></p>}
      <p>Current color: {state.currentColor}</p>
      <p>
        Direction: {state.currentDirection === 'clockwise' ? 'Clockwise' : 'Counterclockwise'}
      </p>
    </div>

    <div className="piles">
      <div className="pile">
        <h3>Draw pile</h3>
        <div className="draw-pile">
          <strong>UNO</strong>
          <span>{state.drawPileSize} cards</span>
        </div>
      </div>
      <div className="pile">
        <h3>Discard pile</h3>
        <UnoCard card={state.topCard} />
      </div>
    </div>

    <section>
      <h3>
        {state.players[state.playerIndex]} — your hand ({state.hand.length} cards)
      </h3>
      <div className="hand">
        {state.hand.map((card, index) =>
          <button
            key={index}
            className="hand-card"
            disabled={busy || !state.playableCards.includes(index) || selectedCard !== undefined}
            onClick={() => selectCard(index)}
          >
            <UnoCard card={card} />
          </button>)}
      </div>
    </section>

    {selectedCard !== undefined &&
      <section className="color-choice" aria-label="Choose a wild card color">
        <h3>Choose a color</h3>
        {colors.map(color =>
          <button
            key={color}
            disabled={busy}
            onClick={() =>
            {
              onPlay(selectedCard, color)
              setSelectedCard(undefined)
            }}
          >
            {color}
          </button>)}
        <button onClick={() => setSelectedCard(undefined)}>Cancel</button>
      </section>}

    {inTurn && state.drawnCardIndex != null && <p>Play the drawn card or pass.</p>}

    {mustAnswer &&
      <section className="challenge" aria-label="Wild Draw Four decision">
        <p>You were given a Wild Draw Four. Challenge it or accept the four-card penalty.</p>
        <button disabled={busy} onClick={onChallenge}>Challenge</button>
        <button disabled={busy} onClick={onAccept}>Accept and draw four</button>
      </section>}

    <div className="actions">
      <button
        disabled={busy || !inTurn || mustAnswer || state.drawnCardIndex != null || selectedCard !== undefined}
        onClick={onDraw}
      >
        Draw card
      </button>
      <button
        disabled={busy || !inTurn || mustAnswer || state.drawnCardIndex == null || selectedCard !== undefined}
        onClick={onPass}
      >
        Pass
      </button>
      <button
        disabled={busy || mustAnswer || (!(inTurn && state.hand.length === 2) && state.unoVulnerablePlayer !== state.playerIndex)}
        onClick={onUno}
      >
        UNO!
      </button>
    </div>
  </section>
}

// src/components/GameBoard.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { colors, type Color } from '../model/deck'
import type { BoardState } from '../model/board'
import UnoCard from './UnoCard.vue'

//#region Props and events

const props = defineProps<{
  state: BoardState
  busy?: boolean
}>()

const emit = defineEmits<{
  play: [index: number, color?: Color]
  draw: []
  pass: []
  uno: []
  catchUno: [player: number]
  challenge: []
  accept: []
}>()

//#endregion

//#region Card selection

const selectedCard = ref<number | undefined>(undefined)
const opponents = computed(() => props.state.players
  .map((name, index) => ({ name, index }))
  .filter(player => player.index !== props.state.playerIndex))
const inTurn = computed(() => props.state.playerInTurn === props.state.playerIndex)
const mustAnswerWildDrawFour = computed(() =>
  props.state.wildDrawFourChallenger === props.state.playerIndex
)

watch(() => props.state, () =>
{
  selectedCard.value = undefined
})

function selectCard(index: number): void
{
  if (props.busy || !props.state.playableCards.includes(index)) return

  const card = props.state.hand[index]

  if ('color' in card)
  {
    emit('play', index)
  }
  else
  {
    selectedCard.value = index
  }
}

function chooseColor(color: Color): void
{
  if (selectedCard.value === undefined) return

  emit('play', selectedCard.value, color)
  selectedCard.value = undefined
}

//#endregion
</script>

<template>
  <section class="game-board">
    <h2>Round in progress</h2>

    <div class="opponents">
      <article
        v-for="{ name, index } in opponents"
        :key="index"
        class="opponent"
        :class="{ active: state.playerInTurn === index }"
      >
        <h3>{{ name }}</h3>

        <p>{{ state.handSizes[index] }} cards</p>

        <span v-if="state.playerInTurn === index">
          In turn
        </span>

        <button
          v-if="state.handSizes[index] === 1"
          type="button"
          :disabled="busy"
          @click="emit('catchUno', index)"
        >
          Catch missed UNO
        </button>
      </article>
    </div>

    <div class="round-status" aria-live="polite">
      <p v-if="state.playerInTurn != null">
        <strong>
          {{ state.players[state.playerInTurn] }}'s turn
        </strong>
      </p>

      <p>Current color: {{ state.currentColor }}</p>

      <p>
        Direction:
        {{ state.currentDirection === 'clockwise'
          ? 'Clockwise'
          : 'Counterclockwise' }}
      </p>
    </div>

    <div class="piles">
      <div class="pile">
        <h3>Draw pile</h3>

        <div class="draw-pile">
          <strong>UNO</strong>
          <span>{{ state.drawPileSize }} cards</span>
        </div>
      </div>

      <div class="pile">
        <h3>Discard pile</h3>

        <UnoCard
          :card="state.topCard"
        />
      </div>
    </div>

    <section>
      <h3>
        {{ state.players[state.playerIndex] }} — your hand
        ({{ state.hand.length }} cards)
      </h3>

      <div class="hand">
        <button
          v-for="(card, index) in state.hand"
          :key="index"
          type="button"
          class="hand-card"
          :disabled="busy || !state.playableCards.includes(index) || selectedCard !== undefined"
          @click="selectCard(index)"
        >
          <UnoCard :card="card" />
        </button>
      </div>
    </section>

    <section v-if="selectedCard !== undefined" class="color-choice" aria-label="Choose a wild card color">
      <h3>Choose a color</h3>
      <button v-for="color in colors" :key="color" type="button" :disabled="busy" @click="chooseColor(color)">
        {{ color }}
      </button>
      <button type="button" @click="selectedCard = undefined">Cancel</button>
    </section>

    <p v-if="inTurn && state.drawnCardIndex != null">
      Play the drawn card or pass.
    </p>

    <section v-if="mustAnswerWildDrawFour" class="challenge" aria-label="Wild Draw Four decision">
      <p>You were given a Wild Draw Four. Challenge it or accept the four-card penalty.</p>
      <button type="button" :disabled="busy" @click="emit('challenge')">Challenge</button>
      <button type="button" :disabled="busy" @click="emit('accept')">Accept and draw four</button>
    </section>

    <div class="actions">
      <button
        type="button"
        :disabled="busy || !inTurn || mustAnswerWildDrawFour || state.drawnCardIndex != null || selectedCard !== undefined"
        @click="emit('draw')"
      >
        Draw card
      </button>
      <button
        type="button"
        :disabled="busy || !inTurn || mustAnswerWildDrawFour || state.drawnCardIndex == null || selectedCard !== undefined"
        @click="emit('pass')"
      >
        Pass
      </button>
      <button
        type="button"
        :disabled="busy || mustAnswerWildDrawFour || (!(inTurn && state.hand.length === 2) && state.unoVulnerablePlayer !== state.playerIndex)"
        @click="emit('uno')"
      >
        UNO!
      </button>
    </div>
  </section>
</template>

<style scoped>
.game-board
{
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.opponents
{
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
}

.opponent
{
  min-width: 120px;
  padding: 16px;
  border: 2px solid #ddd;
  border-radius: 8px;
}

.opponent.active
{
  border-color: #1d4ed8;
  background-color: #eff6ff;
}

.opponent h3
{
  margin-top: 0;
}

.round-status p
{
  margin: 6px 0;
}

.piles
{
  display: flex;
  flex-wrap: wrap;
  gap: 40px;
}

.pile h3
{
  margin-top: 0;
}

.draw-pile
{
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 16px;
  width: 100px;
  height: 150px;
  color: white;
  background-color: #222;
  border: 3px solid white;
  border-radius: 12px;
  box-shadow: 0 2px 6px #0003;
}

.hand
{
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
}

button
{
  padding: 12px;
  font: inherit;
  cursor: pointer;
}

button:disabled
{
  cursor: not-allowed;
  opacity: 0.55;
}

.hand-card
{
  padding: 0;
  border: 0;
  border-radius: 12px;
  background: transparent;
}

.hand-card:focus-visible
{
  outline: 3px solid #222;
  outline-offset: 3px;
}

.actions,
.color-choice,
.challenge
{
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
}

.color-choice h3
{
  width: 100%;
}
</style>
