// src/components/LocalGame.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, shallowRef, triggerRef } from 'vue'
import GameSetup from './GameSetup.vue'
import GameBoard from './GameBoard.vue'
import GameOver from './GameOver.vue'
import { UnoRound } from '../model/round'
import { createBoard } from '../model/board'
import { standardRandomizer } from '../utils/random_utils'
import type { Color } from '../model/deck'
import type { BotRequest, BotResponse } from '../bots/bot'

//#region State

const round = shallowRef<UnoRound | undefined>(undefined)
const message = ref('')
let botTimer: ReturnType<typeof setTimeout> | undefined
let bots: Worker[] = []
let requestId = 0

const state = computed(() =>
{
  return round.value?.toMemento()
})

const board = computed(() =>
{
  return round.value ? createBoard(round.value, 0) : undefined
})

//#endregion

//#region Round setup

function startRound(players: string[]): void
{
  stopBots()
  round.value = UnoRound.create({
    players,
    dealer: standardRandomizer(players.length)
  })
  for (let player = 1; player < players.length; player++)
  {
    const bot = new Worker(new URL('../bots/bot.worker.ts', import.meta.url), { type: 'module' })

    bot.onmessage = (event: MessageEvent<BotResponse>) => receiveBotAction(player, event.data)
    bot.onerror = () =>
    {
      stopBots()
      message.value = 'Bot error. Start a new round from setup.'
    }

    bots.push(bot)
  }
  message.value = ''
  scheduleBot()
}

function returnToSetup(): void
{
  stopBots()
  round.value = undefined
  message.value = ''
}

onUnmounted(stopBots)

//#endregion

//#region Player actions

function updateRound(action: () => void): void
{
  try
  {
    message.value = ''
    action()
    triggerRef(round)
    scheduleBot()
  }
  catch (error)
  {
    message.value = error instanceof Error ? error.message : 'Cannot complete that action'
  }
}

function playCard(index: number, color?: Color): void
{
  if (round.value?.playerInTurn() !== 0) return

  updateRound(() => round.value!.play(index, color))
}

function drawCard(): void
{
  if (round.value?.playerInTurn() !== 0) return

  updateRound(() => round.value!.draw())
}

function passTurn(): void
{
  if (round.value?.playerInTurn() !== 0) return

  updateRound(() => round.value!.pass())
}

function sayUno(): void
{
  if (!round.value || round.value.hasEnded()) return

  updateRound(() => round.value!.sayUno(0))
  message.value = 'You said UNO!'
}

function catchUno(player: number): void
{
  if (!round.value || round.value.hasEnded()) return

  updateRound(() =>
  {
    const caught = round.value!.catchUnoFailure({ accuser: 0, accused: player })

    message.value = caught ? `${round.value!.player(player)} draws four cards` : 'No missed UNO to catch'
  })
}

function challengeWildDrawFour(): void
{
  if (!round.value) return

  updateRound(() =>
  {
    const challenger = round.value!.playerInTurn()!
    const caught = round.value!.challengeWildDrawFour(challenger)
    message.value = caught
      ? 'Challenge successful. The player who played the card draws four.'
      : 'Challenge unsuccessful. You draw six cards.'
  })
}

function acceptWildDrawFour(): void
{
  if (!round.value) return

  updateRound(() =>
  {
    const challenger = round.value!.playerInTurn()!
    round.value!.acceptWildDrawFour(challenger)
    message.value = 'You accepted the penalty and drew four cards.'
  })
}

//#endregion

//#region Bot turns

function scheduleBot(): void
{
  clearTimeout(botTimer)
  requestId++

  const player = round.value?.playerInTurn()

  if (round.value?.hasEnded())
  {
    stopBots()
    return
  }

  if (player !== undefined && player !== 0)
  {
    botTimer = setTimeout(() =>
    {
      const request: BotRequest = { id: requestId, state: round.value!.toMemento() }

      bots[player - 1].postMessage(request)
    }, 1000)
  }
}

function stopBots(): void
{
  clearTimeout(botTimer)
  requestId++

  for (const bot of bots)
  {
    bot.terminate()
  }

  bots = []
}

function receiveBotAction(player: number, response: BotResponse): void
{
  const currentRound = round.value

  if (!currentRound || response.id !== requestId || currentRound.playerInTurn() !== player) return

  updateRound(() =>
  {
    const action = response.action
    const name = currentRound.player(player)

    if (action.type === 'CATCH')
    {
      currentRound.catchUnoFailure({ accuser: player, accused: action.player })
      message.value = `${name} caught ${currentRound.player(action.player)}. Four cards drawn.`
    }
    else if (action.type === 'CHALLENGE')
    {
      const successful = currentRound.challengeWildDrawFour(player)
      message.value = successful
        ? `${name} successfully challenged the Wild Draw Four.`
        : `${name}'s challenge failed and they draw six cards.`
    }
    else if (action.type === 'ACCEPT')
    {
      currentRound.acceptWildDrawFour(player)
      message.value = `${name} accepted the Wild Draw Four and drew four cards.`
    }
    else if (action.type === 'DRAW')
    {
      currentRound.draw()
      message.value = `${name} drew a card`
    }
    else if (action.type === 'PASS')
    {
      currentRound.pass()
      message.value = `${name} passed`
    }
    else
    {
      if (action.sayUno)
      {
        currentRound.sayUno(player)
      }

      currentRound.play(action.index, action.color)
      message.value = action.sayUno ? `${name} said UNO!` : `${name} played a card`
    }
  })
}

//#endregion
</script>

<template>
  <section>

    <GameSetup
      v-if="!state"
      @start="startRound"
    />

    <GameOver
      v-else-if="state.playerInTurn === undefined"
      :winner="state.players[round!.winner()!]"
      :score="round!.score()!"
      @restart="startRound(state.players)"
      @setup="returnToSetup"
    />

    <template v-else>
      <GameBoard
        :state="board!"
        @play="playCard"
        @draw="drawCard"
        @pass="passTurn"
        @uno="sayUno"
        @catch-uno="catchUno"
        @challenge="challengeWildDrawFour"
        @accept="acceptWildDrawFour"
      />

      <p role="status">{{ message }}</p>

      <button type="button" @click="returnToSetup">
        Back to setup
      </button>
    </template>
  </section>
</template>

<style scoped>
button
{
  padding: 12px;
  font: inherit;
  cursor: pointer;
}
</style>

// src/components/LocalGame.tsx
import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import {
  acceptWildDrawFour, catchUnoFailure, challengeWildDrawFour, draw,
  hasEnded, pass, play, sayUno, score, winner, type Round
} from '../model/round'
import { chooseAction } from '../bots/bot'
import { createBoard } from '../model/board'
import { localActions, type AppDispatch, type RootState } from '../store'
import type { Color } from '../model/deck'
import GameBoard from './GameBoard'

export default function LocalGame()
{
  const dispatch = useDispatch<AppDispatch>()
  const { round, message } = useSelector((state: RootState) => state.local)
  const [name, setName] = useState('')
  const [botCount, setBotCount] = useState(1)

  function update(action: (round: Round) => Round, success = ''): void
  {
    if (!round) return
    try
    {
      const next = action(round)
      dispatch(localActions.updateLocalRound({ round: next, message: success }))
    }
    catch (error)
    {
      dispatch(localActions.setLocalMessage(error instanceof Error ? error.message : 'Cannot complete that action'))
    }
  }

  function botTurn(current: Round): void
  {
    const player = current.playerInTurn
    if (player === undefined) return
    const action = chooseAction(current)
    const playerName = current.players[player]
    let next = current
    let status = ''

    if (action.type === 'CATCH')
    {
      next = catchUnoFailure({ accuser: player, accused: action.player }, current)
      status = `${playerName} caught ${current.players[action.player]}. Four cards drawn.`
    }
    else if (action.type === 'CHALLENGE')
    {
      const challenge = current.wildDrawFourChallenge!
      const offenderHadColor = current.hands[challenge.offender]
        .some(card => 'color' in card && card.color === challenge.previousColor)
      next = challengeWildDrawFour(player, current)
      status = offenderHadColor
        ? `${playerName} successfully challenged the Wild Draw Four.`
        : `${playerName}'s challenge failed and they draw six cards.`
    }
    else if (action.type === 'ACCEPT')
    {
      next = acceptWildDrawFour(player, current)
      status = `${playerName} accepted the Wild Draw Four and drew four cards.`
    }
    else if (action.type === 'DRAW')
    {
      next = draw(current)
      status = `${playerName} drew a card`
    }
    else if (action.type === 'PASS')
    {
      next = pass(current)
      status = `${playerName} passed`
    }
    else
    {
      if (action.sayUno) next = sayUno(player, next)
      next = play(action.index, action.color, next)
      status = action.sayUno ? `${playerName} said UNO!` : `${playerName} played a card`
    }
    dispatch(localActions.updateLocalRound({ round: next, message: status }))
  }

  useEffect(() =>
  {
    if (!round || round.playerInTurn === undefined || round.playerInTurn === 0) return
    const timer = window.setTimeout(() =>
    {
      try { botTurn(round) }
      catch (error) { dispatch(localActions.setLocalMessage(error instanceof Error ? error.message : 'Bot error')) }
    }, 700)
    return () => window.clearTimeout(timer)
  }, [round])

  if (!round)
  {
    return <section>
      <h2>Game setup</h2>
      <form className="setup-form" onSubmit={event =>
      {
        event.preventDefault()
        const players = [name.trim(), ...Array.from({ length: botCount }, (_, index) => `Bot ${index + 1}`)]
        dispatch(localActions.startLocalGame({ players, dealer: Math.floor(Math.random() * players.length) }))
      }}>
        <label htmlFor="player-name">Your name</label>
        <input
          id="player-name"
          value={name}
          onChange={event => setName(event.target.value)}
          maxLength={30}
          placeholder="Enter your name"
          required
        />
        <label htmlFor="bot-count">Number of bots</label>
        <select id="bot-count" value={botCount} onChange={event => setBotCount(Number(event.target.value))}>
          <option value={1}>1 bot</option><option value={2}>2 bots</option><option value={3}>3 bots</option>
        </select>
        <button type="submit" disabled={!name.trim()}>Start round</button>
      </form>
    </section>
  }

  if (hasEnded(round))
  {
    return <section aria-labelledby="result-title">
      <h2 id="result-title">Round over</h2>
      <p>{round.players[winner(round)!]} won!</p><p>Round score: {score(round)}</p>
      <div className="actions">
        <button onClick={() => dispatch(localActions.startLocalGame({
          players: [...round.players],
          dealer: Math.floor(Math.random() * round.players.length)
        }))}>
          Play again
        </button>
        <button onClick={() => dispatch(localActions.stopLocalGame())}>Back to setup</button>
      </div>
    </section>
  }

  return <section>
    <GameBoard state={createBoard(round, 0)}
      onPlay={(index: number, color?: Color) => update(value => play(index, color, value), 'You played a card')}
      onDraw={() => update(draw, 'You drew a card')}
      onPass={() => update(pass, 'You passed')}
      onUno={() => update(value => sayUno(0, value), 'You said UNO!')}
      onCatch={player =>
      {
        const next = catchUnoFailure({ accuser: 0, accused: player }, round)
        dispatch(localActions.updateLocalRound({
          round: next,
          message: next === round ? 'No missed UNO to catch' : `${round.players[player]} draws four cards`
        }))
      }}
      onChallenge={() =>
      {
        const challenge = round.wildDrawFourChallenge
        if (!challenge) return
        const offenderHadColor = round.hands[challenge.offender]
          .some(card => 'color' in card && card.color === challenge.previousColor)
        const message = offenderHadColor
          ? 'Challenge successful. The player who played the card draws four.'
          : 'Challenge unsuccessful. You draw six cards.'
        update(value => challengeWildDrawFour(value.playerInTurn!, value), message)
      }}
      onAccept={() => update(
        value => acceptWildDrawFour(value.playerInTurn!, value),
        'You accepted the penalty and drew four cards.'
      )} />
    <p role="status">{message}</p>
    <button onClick={() => dispatch(localActions.stopLocalGame())}>Back to setup</button>
  </section>
}
